/* 140. PL/SQL 변수 이해하기 ② */

SET SERVEROUTPUT ON
ACCEPT P_EMPNO PROMPT '사원번호 입력'

DECLARE
    V_SAL NUMBER(10);
BEGIN
    SELECT SAL INTO V_SAL
    FROM EMP
    WHERE EMPNO = &P_EMPNO;

DBMS_OUTPUT.PUT_LINE('해당 사원의 월급 : ' || V_SAL);

END;
