/*142. PL/SQL IF 이해하기 ② (IF ~ ELSIF ~ ELSE문)*/

SET SERVEROUTPUT ON
SET VERIFY OFF
ACCEPT P_ENAME PROMPT '사원 이름 입력'
DECLARE 
    V_ENAME EMP.ENAME%TYPE := UPPER('&P_ENAME');
    V_SAL EMP.SAL%TYPE;

BEGIN 
    SELECT SAL INTO V_SAL
    FROM EMP
    WHERE ENAME = V_ENAME;
    
    IF V_SAL >= 3000 THEN
        DBMS_OUTPUT.PUT_LINE('고소득자');
    ELSIF V_SAL >= 2000 THEN
        DBMS_OUTPUT.PUT_LINE('중간 소득자');
    ELSE
        DBMS_OUTPUT.PUT_LINE('저소득자');
    END IF;
END;
