/* 88. 서브쿼리를 사용하여 데이터 합치기 */

ALTER TABLE DEPT ADD SUMSAL NUMBER(10);

MERGE INTO DEPT D
USING (
    SELECT
        DEPTNO,
        SUM(SAL) SUMSAL
    FROM
        EMP
    GROUP BY
        DEPTNO
) V ON ( D.DEPTNO = V.DEPTNO )
WHEN MATCHED THEN UPDATE
SET D.SUMSAL = V.SUMSAL;

/* DEPT 테이블 조회 */
SELECT * FROM DEPT;

/* MERGE 없이 수행한 쿼리는 다음과 같다 */

UPDATE DEPT D
SET SUMSAL = (SELECT SUM(SAL) FROM EMP E WHERE E.DEPTNO = D.DEPTNO);

ROLLBACK;