/* 94. 임시 테이블 생성하기 CREATE TEMPORARY TABLE */

/* COMMIT할 때까지만 데이터를 저장할 수 있도록 테이블 생성*/

CREATE GLOBAL TEMPORARY TABLE EMP37 (
    EMPNO NUMBER(10),
    ENAME VARCHAR2(10),
    SAL   NUMBER(10)
) ON COMMIT DELETE ROWS;

/*
ON COMMIT DELETE ROWS  : COMMIT할 때까지만 데이터 보관
ON COMMIT PRESERVE ROWS : 세션이 종료될 때까지 데이터를 보관 

*/

INSERT INTO EMP37 VALUES(1111,'SCOTT',3000);
INSERT INTO EMP37 VALUES(2222,'SMITH',2000);
SELECT * FROM EMP37;
COMMIT;

CREATE GLOBAL TEMPORARY TABLE EMP38 (
    EMPNO NUMBER(10),
    ENAME VARCHAR2(10),
    SAL   NUMBER(10)
) ON COMMIT PRESERVE ROWS;

INSERT INTO EMP38 VALUES(1111,'SCOTT',3000);
INSERT INTO EMP38 VALUES(2222,'SMITH',2000);

SELECT * FROM EMP38;
COMMIT;

EXIT;
