/*138. 남자와 여자가 각각 많이 걸리는 암은*/

DROP  TABLE  CANCER;

CREATE  TABLE  CANCER
( 암종       VARCHAR2(50),   
  질병코드   VARCHAR2(20),
  환자수     NUMBER(10),
  성별       VARCHAR2(20),
  조유병률   NUMBER(10,2),     
  생존률    NUMBER(10,2) ); SELECT DISTINCT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    암종
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    성별
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    환자수
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FROM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CANCER
                                                                                                                                                                                                                                                                                                                                                                                                            WHERE
                                                                                                                                                                                                                                                                                                                                                                                                                환자수 = (
                                                                                                                                                                                                                                                                                                                                                                                                                    SELECT
                                                                                                                                                                                                                                                                                                                                                                                                                        MAX
                                                                                                                                                                                                                                                                                                                                                                                                                        (
                                                                                                                                                                                                                                                                                                                                                                                                                        환자수
                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                    FROM
                                                                                                                                                                                                                                                                                                                                                                                                                        CANCER
                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE
                                                                                                                                                                                                                                                                                                                                                                                                                            성별 = '남자'
                                                                                                                                                                                                                                                                                                                                                                                                                        AND
                                                                                                                                                                                                                                                                                                                                                                                                                        암종 != '모든암'
                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                        UNION
                                                                                                                                                                                                                                                                        ALL
                                                                                                                                                                                                                                                                        SELECT
                                                                                                                                                                                                                                                                        DISTINCT
                                                                                                                                                                                                                                                                            (
                                                                                                                                                                                                                                                                            암종
                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                            성별
                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                            환자수
                                                                                                                                                                                                                                                                        FROM
                                                                                                                                                                                                                                                                            CANCER
                                                                                                                                    WHERE
                                                                                                                                        환자수 = (
                                                                                                                                            SELECT
                                                                                                                                                MAX
                                                                                                                                                (
                                                                                                                                                환자수
                                                                                                                                                )
                                                                                                                                            FROM
                                                                                                                                                CANCER
                                                                                                                                            WHERE
                                                                                                                                                    성별 = '여자'
                                                                                                                                                AND
                                                                                                                                                암종 != '모든암'
                                                                                                                                        )