-- ROW를 COLUMN으로 출력하기 1 (SUM + DECODE)

SELECT
    SUM(DECODE(DEPTNO, 10, SAL)) AS "10",
    SUM(DECODE(DEPTNO, 20, SAL)) AS "20",
    SUM(DECODE(DEPTNO, 30, SAL)) AS "30"
FROM
    EMP;
    
-- 직업, 직업별 토탈 월급 가로로 출력

SELECT
    SUM(DECODE(JOB, 'ANALYST', SAL))  AS "ANALYST",
    SUM(DECODE(JOB, 'CLERK', SAL))    AS "CLERK",
    SUM(DECODE(JOB, 'MANAGER', SAL))  AS "MANAGER",
    SUM(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
FROM
    EMP;

SELECT
    DEPTNO,
    SUM(DECODE(JOB, 'ANALYST', SAL))  AS "ANALYST",
    SUM(DECODE(JOB, 'CLERK', SAL))    AS "CLERK",
    SUM(DECODE(JOB, 'MANAGER', SAL))  AS "MANAGER",
    SUM(DECODE(JOB, 'SALESMAN', SAL)) AS "SALESMAN"
FROM
    EMP
GROUP BY
    DEPTNO;