/* 151. 함수 구현하기 */

CREATE OR REPLACE FUNCTION GET_LOC (
    P_DEPTNO IN DEPT.DEPTNO%TYPE
) RETURN DEPT.LOC%TYPE IS
    V_LOC DEPT.LOC%TYPE;
BEGIN
    SELECT
        LOC INTO V_LOC
    FROM
        DEPT
    WHERE
        DEPTNO = P_DEPTNO;
    RETURN V_LOC;
END;

SELECT
    ENAME,
    GET_LOC(DEPTNO) AS LOC
FROM
    EMP
WHERE
    JOB = 'SALESMAN';
    