/* 130. 우리나라에서 대학 등록금이 가장 높은 학교는 어디인가? */

DROP TABLE UNIVERSITY_FEE;

CREATE TABLE UNIVERSITY_FEE
(DIVISION       VARCHAR2(20),
 TYPE           VARCHAR2(20),
 UNIVERSITY     VARCHAR2(60),
 LOC            VARCHAR2(40),
 ADMISSION_CNT  NUMBER(20),
 ADMISSION_FEE   NUMBER(20),
 TUITION_FEE      NUMBER(20) ) ;
 
commit;
 
SELECT *
 FROM ( 
   SELECT UNIVERSITY, TUITION_FEE , 
             RANK() OVER (ORDER BY TUITION_FEE DESC NULLS LAST) 순위
      FROM UNIVERSITY_FEE
      )
 WHERE 순위 =1 ;
 