/* 102.실수로 지운 데이터 복구하기 ④ (FLASHBACK VERSION QUERY)*/


SELECT
    ENAME,
    SAL,
    VERSIONS_STARTTIME,
    VERSIONS_ENDTIME,
    VERSIONS_OPERATION
FROM
    EMP VERSIONS BETWEEN TIMESTAMP TO_TIMESTAMP('2023-12-25 00:20:00', 'RRRR-MM-DD HH24,MI:SS') AND MAXVALUE
WHERE
    ENAME = 'KING'
ORDER BY
    VERSIONS_STARTTIME;