/*104. 데이터의 품질 높이기 ①(PRIMARY KEY)*/

CREATE TABLE DEPT2 (
    DEPTNO NUMBER(10)
        CONSTRAINT DEPT2_DEPNO_PK PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(10)
);

/* 
이미 있는 DEPTNO 에 대해서는 중복으로 입력 불가능
아래는 테이블에 생성된 제약을 확인
*/
SELECT
    UC.CONSTRAINT_NAME,
    UC.CONSTRAINT_TYPE,
    UCC.COLUMN_NAME
FROM
    USER_CONSTRAINTS  UC,
    USER_CONS_COLUMNS UCC
WHERE
        UC.TABLE_NAME = 'DEPT2'
    AND UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME;
    
/* 
ALTER TABLE DEPT2 ADD CONSTRAINT DEPT2_DEPTNO_PK PRIMARY KEY(DEPTNO);로 추후에 추가도 가능
*/    