/* 최대값 출력하기(MAX) */
SELECT MAX(SAL)
FROM EMP;

SELECT MAX(SAL)
FROM EMP
WHERE JOB = 'SALESMAN';

/* NOT A SINGLE_GROUP FUNCTION ERROR */
SELECT JOB, MAX(SAL)
FROM EMP
WHERE JOB='SALESMAN';

SELECT JOB, MAX(SAL)
FROM EMP
WHERE JOB='SALESMAN'
GROUP BY JOB;

/* SQL 실행 순서 FROM > WHERE > GROUP BY JOB > SELECT */
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;
